### ISSUE TITLE
CNN Dailymail Dataset

### ISSUE THREAD

**Issue by syedzubeen** [DagsHub/open-source-ml-datasets#60]
Dataset Details:
The CNN/DailyMail Dataset, composed of approximately 300,000 distinct news articles authored by journalists from CNN and the Daily Mail, primarily facilitates extractive and abstractive summarization. Nevertheless, its initial purpose was to aid machine reading and comprehension, as well as abstractive question answering.

Dataset URL:
https://huggingface.co/datasets/ccdv/cnn_dailymail

**Comment by yonomitt** [comment]
Closed by #62
